FROM docker:20.10.14-dind as builder
RUN apk add skopeo
RUN skopeo copy docker://moby/buildkit:buildx-stable-1 docker-archive:/tmp/moby-buildkit-buildx-stable-1.tar:moby/buildkit:buildx-stable-1

FROM docker:20.10.14-dind

COPY --from=docker/buildx-bin:0.18.0 /buildx /usr/local/bin/buildx
COPY --from=builder /tmp/moby-buildkit-buildx-stable-1.tar /tmp/moby-buildkit-buildx-stable-1.tar

ENV DOCKER_HOST=unix:///var/run/docker.sock

ADD release/linux/amd64/drone-docker /bin/
ENTRYPOINT ["/usr/local/bin/dockerd-entrypoint.sh", "/bin/drone-docker"]
