FROM docker:27.4.1-dind

ARG TARGETOS
ARG TARGETARCH

ENV DOCKER_HOST=unix:///var/run/docker.sock

RUN mkdir -p /etc/buildkit

ADD release/$TARGETOS/$TARGETARCH/dockerbuildkit /bin/

ENTRYPOINT ["/usr/local/bin/dockerd-entrypoint.sh", "/bin/dockerbuildkit"]